FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Playwright dependencies
RUN playwright install --with-deps chromium

COPY . .

CMD ["fastapi", "run", "main.py", "--port", "8000", "--host", "0.0.0.0"]
